version: '2'

services:
  php:
    image: php:7.1-fpm-alpine
    volumes:
      - ./files/php-fpm.d/zz-docker.conf:/usr/local/etc/php-fpm.d/zz-docker.conf:ro
      - ./html:/var/www/html:ro
      - run:/var/run/:rw

  nginx:
    image: nginx:1.11-alpine
    ports:
      - 9876:80
    volumes:
      - ./files/nginx.d/default.conf:/etc/nginx/conf.d/default.conf:ro
      - ./html:/var/www/html:ro
      - run:/var/run/:rw

volumes:
  run:
